# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9f9f5ed390421db130016532b7f1701234000c6adb3f0274a5db18b6604c4c237b5e3a9f053ec375038ce5cc086f4c10af3427b2552a0e41bce9a28a10b01c5

test:
  secret_key_base: 80dcf4bfbfb486f1fd5a65432753568a428616f11c6b051c9078cccb73c7bfb27144ae3e1ffc32f84a22fc606be038f7f25e98b6bc6ee8b53c5bde8afab18ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
